### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by skarampatakis** [riccardoAlbertoni/qSKOS#5]
Hi, I have built your version as the DQV option sounds very useful but I have this problem. 

qSKOS is running successfully giving output on the old simple text format but with the -DQV option I have this error. Doy you have any hint on this? 

Thank you in advance.

```
Writing results as instances of the Data Quality Vocabulary
java.lang.UnsupportedOperationException
	at at.ac.univie.mminf.qskos4j.result.Result.occurrenceCount(Result.java:65)
	at at.ac.univie.mminf.qskos4j.cmd.ReportCollector.writeDQVReport(ReportCollector.java:216)
	at at.ac.univie.mminf.qskos4j.cmd.ReportCollector.writeDQVReportBody(ReportCollector.java:268)
	at at.ac.univie.mminf.qskos4j.cmd.ReportCollector.outputIssuesReport(ReportCollector.java:78)
	at at.ac.univie.mminf.qskos4j.cmd.VocEvaluate.evaluate(VocEvaluate.java:206)
	at at.ac.univie.mminf.qskos4j.cmd.VocEvaluate.listIssuesOrEvaluate(VocEvaluate.java:166)
	at at.ac.univie.mminf.qskos4j.cmd.VocEvaluate.<init>(VocEvaluate.java:121)
	at at.ac.univie.mminf.qskos4j.cmd.VocEvaluate.main(VocEvaluate.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
```

**Comment by riccardoAlbertoni** [comment]
Hi, 
 I am not sure to understand why you got this.
It would be helpful if you provide me the  exact command line you have used.

Thanks, 
Riccardo

**Comment by skarampatakis** [comment]
Hi,
the command is the following
```
java -jar qSKOS-cmd.jar analyze -DQV -dc mil,bl -o out.txt  ~/Desktop/esf_2007_2013_czech_operational_programmes.ttl
```
where the SKOS to analyze is [this](https://github.com/openbudgets/datasets/blob/master/ESF-CZ/2007-2013/projects/codelists/esf_2007_2013_czech_operational_programmes.trig) .

I have tested with another SKOS vocabulary and it is working but I want to know what is the problem with this particular one. 

Thank you in advance.

**Comment by riccardoAlbertoni** [comment]
Hi,
As far as I could understand there are issues such as "No Common Languages", for which, qskos does not  count the number  of  concepts exhibiting the Issue.
As a consequence of this,  qskos raises an exception when my procedure call  the method to count the  problematic concepts ;) 
I have fixed  this in a proper commit, caching the exception and mapping the quality values for this kind of issue into boolean.  Let me know if you notice  anything strange.
Thanks, 
Riccardo

**Comment by skarampatakis** [comment]
Hi,

I just tested the fix and it is working. Thank you a lot. But I have another question. Could it be possible to include along with the metrics the descriptions? On the output of qSKOS on every metric there is a description and a label eg 
```
--- Incomplete Language Coverage
Description: Finds concepts lacking description in languages that are present for other concepts
Detailed information: https://github.com/cmader/qSKOS/wiki/Quality-Issues#incomplete-language-coverage
count: 0
```
Could these be included within DQV triples?

**Comment by skarampatakis** [comment]
Nevermind. I just realised that DQV is a DataCube. So it's dimension labels will be on  qSKOS/src/main/resources/DQVMetricsDimensionForQSKOS.ttl. So I could retrieve them from there, is this true?

**Comment by riccardoAlbertoni** [comment]
An example of query for retrieving the info you asked about is the following. Hope it might helps. 

```
prefix dqv: <http://www.w3.org/ns/dqv#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
select distinct ?measurement ?val  ?metric  ?MetricLabel ?MetricDefinition {
   ?measurement  dqv:value ?val.
    OPTIONAL { 
        ?measurement dqv:isMeasurementOf ?metric.
        Optional {?metric skos:prefLabel ?MetricLabel} 
        Optional{ ?metric skos:definition ?MetricDefinition .}
    }
}
